Feature branch
dibdas/newyork-times-clone pull request #3
Opened 2020-08-28 15:35 UTC by dibdas

NY TIMES clone project review request..

2020-08-28 17:15 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] Fix your linting errors

* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ]  **The Theory of Inflation** section should be one picture with texts in it

## Optional

- [ ] use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-28 17:15 UTC, Spayco commented on index.html
> +                  </navbar>
- [ ] The Correct tag name is `<nav>`, not `<navbar>`.

2020-08-31 11:18 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

Hi team :handshake: 

The project looks awesome. Congrats :1st_place_medal: 

Great work implemented what was previously asked :ok_hand: 

You can move forward :100: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-31 11:18 UTC, expjazz commented on README.md
>  This assignment consists of making a clone of a New York Times article page.
- You do not need to say that this was an assignment from a school if you do not want to. I believe it is better to say what you showcased in this project, like: 'We cloned the New York Times Pages using grids, flexbox and ...'

2020-08-31 12:18 UTC, merged